# Generated by Django 2.2.1 on 2019-12-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDEtiqueta', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=30)),
                ('Categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDLocacion', models.CharField(max_length=10)),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('Ciudad', models.CharField(max_length=30)),
                ('Pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDProyecto', models.CharField(max_length=20)),
                ('nombreProyecto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDRol', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDTweet', models.CharField(max_length=10)),
                ('IDConversacion', models.CharField(max_length=10)),
                ('Texto', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Locacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.Locacion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDUser', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Pais', models.CharField(max_length=30)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='UserProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.Proyecto')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.User')),
            ],
        ),
        migrations.CreateModel(
            name='TweetEtiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.Etiqueta')),
                ('Tweet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AdminNewTags.Tweet'),
        ),
    ]
